apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greye.fullname" . }}
  labels:
    {{- include "greye.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "server": {
        "logLevel": "{{ .Values.server.logLevel }}",
        "port": {{ .Values.service.targetPort }},
        "applicationName": "{{ include "greye.fullname" . }}",
        "serviceHAName": "{{ include "greye.fullname" . }}",
        "numberGreye": {{ .Values.replicaCount }}
      },
      "notification": {
        "telegram": {
          "destination": "{{ .Values.notification.telegram.destination }}",
          "token": "{{ .Values.notification.telegram.token }}"
        },
        "email": {
          "destination": "{{ .Values.notification.email.destination }}",
          "token": "{{ .Values.notification.email.token }}"
        }
      },
      "protocol": [
        "http"
        {{- range $index, $element := .Values.protocol }}
        , "{{ $element }}"
        {{- end }}
      ],
      "application": {
        "intervalSeconds": {{ .Values.application.intervalSeconds | default 60  }},
        "timeoutSeconds": {{ .Values.application.timeoutSeconds | default 10  }},
        "protocol": "{{ .Values.application.protocol | default "http" }}",
        "method": "{{ .Values.application.method | default "GET" }}",
        "headers": "{{ .Values.application.headers | default "{}" }}",
        "body": "{{ .Values.application.body | default "{}" }}",
        "port": {{ .Values.service.targetPort | default 80 }},
        "maxFailedRequests": {{ .Values.application.maxFailedRequests | default 3 }},
        "authentication": [
          {{- range $index, $element := .Values.application.authentication }}
            {{- if $index }}, {{ end }}
          "{{ $element }}"
          {{- end }}
        ]
      },
      "cluster": {
        "ip": [
          {{- range $index, $element := .Values.cluster.ip }}
            {{- if $index }}, {{ end }}
          "{{ $element }}"
          {{- end }}
        ],
        "intervalSeconds": {{ .Values.cluster.intervalSeconds | default 60 }},
        "timeoutSeconds": {{ .Values.cluster.timeoutSeconds | default 15 }},
        "maxFailedRequests": {{ .Values.cluster.maxFailedRequests | default 5 }},
        "myIp": "{{ .Values.cluster.myIp }}"
      }
    }
