
{{- if .Values.monitoring.enabled -}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "greye.fullname" . }}
  labels:
    release: prometheus
    {{- include "greye.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
      - path: /metrics
        port: http
  selector:
    matchLabels:
      greye-application: "true"


{{- end }}
